# fly.toml app configuration file generated for svelte-kit on 2024-10-17T12:52:46-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-library'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
