export const BEGIN_FILTER_CHANGE = 'BEGIN_FILTER_CHANGE';
export const TOGGLE_PENDING_SUBJECT = 'TOGGLE_PENDING_SUBJECT';
export const SET_PENDING = 'SET_PENDING';
export const APPLY_PENDING_SEARCH = 'APPLY_PENDING_SEARCH';
export const END_FILTER_CHANGE = 'END_FILTER_CHANGE';
export const SET_FILTERS = 'SET_FILTERS';
export const SET_VIEWING_USERID = 'SET_VIEWING_USERID';