export const BEGIN_FILTER_CHANGE = 'BEGIN_FILTER_CHANGE';
export const TOGGLE_PENDING_SUBJECT = 'TOGGLE_PENDING_SUBJECT';
export const END_FILTER_CHANGE = 'END_FILTER_CHANGE';
export const SET_SORT_DIRECTION = 'SET_SORT_DIRECTION';