type User {
  email: String
  userId: String
  isPublic: Boolean
  publicName: String
  publicBooksHeader: String
}

type PublicUser {
  email: String
  isPublic: Boolean
  publicName: String
  publicBooksHeader: String
}

type UserSingleQueryResult {
  User: User
}

type PublicUserSingleQueryResult {
  PublicUser: User
}

extend type Query {
  getUser: UserSingleQueryResult
  getPublicUser(userId: String): PublicUserSingleQueryResult
}

input UserUpdates {
  isPublic: Boolean
  publicBooksHeader: String
  publicName: String
}

extend type Mutation {
  updateUser(Updates: UserUpdates): UserSingleQueryResult
}
