module.exports = {
    UPDATE_ISBN: 'UPDATE_ISBN',
    GET_BOOK: 'GET_BOOK',
    SAVE_ALL_PENDING: 'SAVE_ALL_PENDING_BOOKS',
    RESET_LIST: 'RESET_LIST',
    SET_PENDING: 'SET_PENDING',
    BOOK_SAVED: 'BOOK_SAVED',
    MANUAL_BOOK_SAVED: 'MANUAL_BOOK_SAVED',
    INCREMENT_PENDING: 'INCREMENT_PENDING',
    BOOK_QUEUED: 'BOOK_QUEUED',
    BOOK_LOOKUP_FAILED: 'BOOK_LOOKUP_FAILED'
};