module.exports = {
    UPDATE_ISBN: 'UPDATE_ISBN',
    CURRENT_INPUT_FINISHED: 'CURRENT_INPUT_FINISHED',
    GET_BOOK: 'GET_BOOK',
    GET_BOOK_RESULTS: 'GET_BOOK_RESULTS',
    DELETE_BOOK: 'DELETE_BOOK',
    BOOK_DELETED: 'BOOK_DELETED',
    BOOK_DELETING: 'BOOK_DELETING',
    SAVE_ALL_PENDING: 'SAVE_ALL_PENDING_BOOKS',
    GETTING_BOOKS: 'GETTING_BOOKS'
};