# fly.toml app configuration file generated for sync-similar-books on 2025-05-18T16:43:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sync-similar-books'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '128GB'
  cpu_kind = 'performance'
  cpus = 16
