export const EDIT_BOOK = 'EDIT_BOOK';
export const STOP_EDITING_BOOK = 'CANCEL_EDIT_BOOK';
export const SAVE_EDITING_BOOK = 'SAVE_EDITING_BOOK';
export const EDITING_BOOK_SAVING = 'EDITING_BOOK_SAVING';
export const EDITING_BOOK_SAVED = 'EDITING_BOOK_SAVED';
export const EDIT_BOOK_RESET = 'EDIT_BOOK_RESET';