'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var EDIT_BOOK = 'EDIT_BOOK';
exports.EDIT_BOOK = EDIT_BOOK;
var STOP_EDITING_BOOK = 'CANCEL_EDIT_BOOK';
exports.STOP_EDITING_BOOK = STOP_EDITING_BOOK;
var SAVE_EDITING_BOOK = 'SAVE_EDITING_BOOK';
exports.SAVE_EDITING_BOOK = SAVE_EDITING_BOOK;
var EDITING_BOOK_SAVING = 'EDITING_BOOK_SAVING';
exports.EDITING_BOOK_SAVING = EDITING_BOOK_SAVING;
var EDITING_BOOK_SAVED = 'EDITING_BOOK_SAVED';
exports.EDITING_BOOK_SAVED = EDITING_BOOK_SAVED;
var EDIT_BOOK_RESET = 'EDIT_BOOK_RESET';
exports.EDIT_BOOK_RESET = EDIT_BOOK_RESET;