export const LOAD_BOOKS = "LOAD_BOOKS";
export const LOAD_BOOKS_RESULTS = "LOAD_BOOKS_RESULTS";
export const TOGGLE_SELECT_BOOK = "TOGGLE_SELECT_BOOK";
export const BOOK_READ_CHANGING = "BOOK_READ_CHANGING";
export const BOOK_READ_CHANGED = "BOOK_READ_CHANGED";
export const TOGGLE_CHECK_ALL = "TOGGLE_CHECK_ALL";

export const SET_PENDING_DELETE_BOOK = "SET_PENDING_DELETE_BOOK";
export const CANCEL_PENDING_DELETE_BOOK = "CANCEL_PENDING_DELETE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const BOOK_DELETING = "BOOK_DELETING";
export const BOOK_DELETED = "BOOK_DELETED";

export const SET_BOOKS_SUBJECTS = "SET_BOOKS_SUBJECTS";
export const SET_BOOKS_TAGS = "SET_BOOKS_TAGS";

export const EDITORIAL_REVIEWS_LOADING = "LOADING_EDITORIAL_REVIEWS";
export const DETAILS_LOADED = "EDITORIAL_REVIEWS_LOADED";
export const EXPAND_BOOK = "EXPAND_BOOK";
export const COLLAPSE_BOOK = "COLLAPSE_BOOK";

export const EDITING_BOOK_SAVED = "EDITING_BOOK_SAVED";
