export const LOAD_BOOKS = 'LOAD_BOOKS';
export const LOAD_BOOKS_RESULTS = 'LOAD_BOOKS_RESULTS';
export const TOGGLE_SELECT_BOOK = 'TOGGLE_SELECT_BOOK';
export const SELECT_ALL_BOOKS = 'SELECT_ALL_BOOKS';
export const BOOK_READ_CHANGING = 'BOOK_READ_CHANGING';
export const BOOK_READ_CHANGED = 'BOOK_READ_CHANGED';
export const TOGGLE_CHECK_ALL = 'TOGGLE_CHECK_ALL';