export const LOAD_COLORS = 'LOAD_COLORS_TAGS';
export const LOAD_TAGS = 'LOAD_TAGS';
export const LOAD_TAGS_RESULTS = 'LOAD_TAGS_RESULTS';

export const UPDATE_TAG = 'UPDATE_TAG';
export const UPDATE_TAG_RESULTS = 'UPDATE_TAG_RESULTS';
export const CLEAR_TAG_MODIFICATION_TAGS = 'CLEAR_TAG_MODIFICATION_TAGS';
export const CANCEL_TAG_MODIFICATION = 'CANCEL_TAG_MODIFICATION';
export const BEGIN_TAG_DELETE = 'BEGIN_TAG_DELETE';
export const TAG_DELETING = 'TAG_DELETING';
export const TAG_DELETED = 'TAG_DELETED';