export const LOAD_SUBJECTS = 'LOAD_SUBJECTS';
export const LOAD_SUBJECTS_RESULTS = 'LOAD_SUBJECTS_RESULTS';
export const LOAD_COLORS = 'LOAD_COLORS';

export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const NEW_SUBJECT = 'NEW_SUBJECT';
export const EDIT_SUBJECTS = 'EDIT_SUBJECTS';
export const SET_NEW_SUBJECT_VALUE = 'SET_NEW_SUBJECT_VALUE';
export const STOP_EDITING_SUBJECTS = 'STOP_EDITING_SUBJECTS';
export const CANCEL_SUBJECT_EDIT = 'CANCEL_SUBJECT_EDIT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const UPDATE_SUBJECT_RESULTS = 'UPDATE_SUBJECT_RESULTS';
export const CANCEL_PENDING_FILTERED_SUBJECTS = 'CANCEL_PENDING_FILTERED_SUBJECTS';
export const CLEAR_SUBJECT_MODIFICATION_SUBJECTS = 'CLEAR_SUBJECT_MODIFICATION_SUBJECTS';
export const CANCEL_SUBJECT_MODIFICATION = 'CANCEL_SUBJECT_MODIFICATION';
export const BEGIN_SUBJECT_DELETE = 'BEGIN_SUBJECT_DELETE';
export const CANCEL_SUBJECT_DELETE = 'CANCEL_SUBJECT_DELETE';
export const SUBJECT_DELETED = 'SUBJECT_DELETED';
