# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: arackaf
service: process-book-cover

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  environment:
    stage: ${self:provider.stage}
    STAGE: ${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:*:*:table/My_Library_${self:provider.stage}"
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: ["arn:aws:s3:::my-library-cover-upload-staging/*", "arn:aws:s3:::my-library-cover-uploads/*"]

functions:
  processCover:
    handler: ./dist/index.handler

build:
  esbuild: false
