export const LOAD_BOOKS = 'LOAD_BOOKS';
export const LOAD_BOOKS_RESULTS = 'LOAD_BOOKS_RESULTS';
export const TOGGLE_SELECT_BOOK = 'TOGGLE_SELECT_BOOK';
export const SELECT_ALL_BOOKS = 'SELECT_ALL_BOOKS';