service: book-covers

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  timeout: 30
  apiGateway:
    binaryMediaTypes:
      - "multipart/form-data"

  # you can overwrite defaults here
  stage: live
  #  region: us-east-1
  environment:
    STAGE: ${self:provider.stage}
    stage: ${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource: ["arn:aws:s3:::my-library-cover-upload-staging/*", "arn:aws:s3:::my-library-cover-uploads/*"]
        - Effect: "Allow"
          Action:
            - "secretsmanager:GetSecretValue"
          Resource: "arn:aws:secretsmanager:us-east-1:*"
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeStream
          Resource: "arn:aws:dynamodb:*:*:table/My_Library_${self:provider.stage}"

functions:
  upload:
    handler: handlerFileUpload.handler
    events:
      - http:
          path: upload
          method: post
          cors: true

  uploadFromUrl:
    handler: handlerUrlUpload.handler
    events:
      - http:
          path: uploadFromUrl
          method: post
          cors: true

  isbnDbBookCoverLookup:
    timeout: 10
    handler: handlerIsbnDbLookup.handler
    events:
      - http:
          path: /isbndb-cover-lookup
          method: post
          cors: true

custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true

package:
  individually: true

plugins:
  - serverless-esbuild
