export const faAngleDoubleDown: IconDefinition;
export const faAngleDoubleUp: IconDefinition;
export const faAngleDown: IconDefinition;
export const faAngleUp: IconDefinition;
export const faArrows: IconDefinition;
export const faBars: IconDefinition;
export const faChartBar: IconDefinition;
export const faCheck: IconDefinition;
export const faCloudUploadAlt: IconDefinition;
export const faMinus: IconDefinition;
export const faPencil: IconDefinition;
export const faPlus: IconDefinition;
export const faPlusSquare: IconDefinition;
export const faQuestionCircle: IconDefinition;
export const faRedo: IconDefinition;
export const faSave: IconDefinition;
export const faSpinner: IconDefinition;
export const faTrash: IconDefinition;
import { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export { IconDefinition, IconLookup, IconName, IconPrefix, IconPack } from '@fortawesome/fontawesome-common-types';
export const prefix: IconPrefix;
export const far: IconPack;