export const SET_SEARCH_VALUES = "home.search.SET_SEARCH";
export const SEARCH_BOOKS = "home.search.SEARCH_BOOKS";
export const SEARCH_BOOKS_COMPLETE = "home.search.SEARCH_BOOKS_COMPLETE";

export const SELECT_BOOK_TO_SEARCH_RECOMMENDATIONS_FOR = "home.SELECT_BOOK_TO_SEARCH_RECOMMENDATIONS_FOR";
export const REMOVE_SELECTED_BOOK = "home.REMOVE_SELECTED_BOOK";
