# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: arackaf
# "service" is the name of this project. This will also be added to your AWS resource names.
service: amazon-sync

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  stage: dev
  environment:
    stage: ${self:provider.stage}
    STAGE: ${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource: "arn:aws:dynamodb:*:*:table/My_Library_${self:provider.stage}"

functions:
  ratingsSync:
    handler: handler.ratingsSync
    timeout: 500
#    events:
#      - schedule: rate(1 hour)

package:
  individually: true
