module.exports = {
    LOAD_BOOKS: 'LOAD_BOOKS',
    LOAD_BOOKS_RESULTS: 'LOAD_BOOKS_RESULTS',
    LOAD_SUBJECTS: 'LOAD_SUBJECTS',
    LOAD_SUBJECTS_RESULTS: 'LOAD_SUBJECTS_RESULTS',
    TOGGLE_SELECT_BOOK: 'TOGGLE_SELECT_BOOK',
    SELECT_ALL_BOOKS: 'SELECT_ALL_BOOKS',
    DE_SELECT_ALL_BOOKS: 'DE_SELECT_ALL_BOOKS',
    EDIT_SUBJECT: 'EDIT_SUBJECT',
    EDIT_SUBJECTS: 'EDIT_SUBJECTS',
    SET_NEW_SUBJECT_NAME: 'SET_NEW_SUBJECT_NAME',
    SET_NEW_SUBJECT_PARENT: 'SET_NEW_SUBJECT_PARENT',
    STOP_EDITING_SUBJECTS: 'STOP_EDITING_SUBJECTS',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',
    UPDATE_SUBJECT_RESULTS: 'UPDATE_SUBJECT_RESULTS',
    TOGGLE_FILTER_SUBJECT: 'TOGGLE_FILTER_SUBJECT'
};