module.exports = {
    LOAD_BOOKS: 'LOAD_BOOKS',
    LOAD_BOOKS_RESULTS: 'LOAD_BOOKS_RESULTS',
    LOAD_SUBJECTS: 'LOAD_SUBJECTS',
    LOAD_SUBJECTS_RESULTS: 'LOAD_SUBJECTS_RESULTS',
    EDIT_SUBJECTS_FOR: 'EDIT_SUBJECTS_FOR',
    MODIFY_SUBJECTS: 'MODIFY_SUBJECTS',
    MODIFY_SUBJECTS_RESULTS: 'MODIFY_SUBJECTS_RESULTS'
};