module.exports = {
    ENABLE_SUBJECT_MODIFICATION_FOR_SINGLE_BOOK: 'ENABLE_SUBJECT_MODIFICATION_FOR_SINGLE_BOOK',
    ENABLE_SUBJECT_MODIFICATION_FOR_TOGGLED_BOOKS: 'ENABLE_SUBJECT_MODIFICATION_FOR_TOGGLED_BOOKS',
    TOGGLE_SUBJECT_ADD_FOR_SUBJECT_MODIFICATION: 'TOGGLE_SUBJECT_ADD_FOR_SUBJECT_MODIFICATION',
    TOGGLE_SUBJECT_REMOVE_FOR_SUBJECT_MODIFICATION: 'TOGGLE_SUBJECT_REMOVE_FOR_SUBJECT_MODIFICATION',
    SETTING_BOOKS_SUBJECTS: 'SETTING_BOOKS_SUBJECTS',
    SET_BOOKS_SUBJECTS: 'SET_BOOKS_SUBJECTS',
    CANCEL_BOOKS_SUBJECT_MODIFICATION: 'CANCEL_BOOKS_SUBJECT_MODIFICATION',
    CLEAR_SUBJECT_MODIFICATION_SUBJECTS: 'CLEAR_SUBJECT_MODIFICATION_SUBJECTS'
};